django_fun/django_fun/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('users/login', views.login_view, name='login'),
    path('users/logout', views.logout_view, name='logout'),
    path('users/registry', views.register, name='register'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')) #products/<id>
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_fun/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product') #id ->primary key
]

django_fun/categories/models.py
from django.db import models
from products.models import Product
# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    products = models.ManyToManyField(Product, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

django_fun/products/models.py
import uuid
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save

class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0)
    slug = models.SlugField(null=False, blank=False, unique=True)
    image = models.ImageField(upload_to='products/', null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    #def save(self, *args, **kwargs):
    #    self.slug = slugify(self.License_plate)
    #    super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs):
    if instance.title and not instance.slug:
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8])
            )
        instance.slug = slug
pre_save.connect(set_slug, sender=Product)

django_fun/django_fun/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(required=True,
                                min_length=4, max_length=50,
                                widget=forms.TextInput(attrs={
                                    'class': 'form-control',
                                    'id': 'username',
                                }))
    email = forms.EmailField(required=True,
                                widget=forms.EmailInput(attrs={
                                    'class': 'form-control',
                                    'id': 'email',
                                    'placeholder': 'example@holbertonschool.com'
                                }))
    password = forms.CharField(required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                }))
    password2 = forms.CharField(label='Confirm password',
                                required=True,
                                widget=forms.PasswordInput(attrs={
                                    'class': 'form-control',
                                }))

    def clean_username(self): #validating user
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is already in use')
        return username

    def clean_email(self): #validating email
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email is already in use')
        return email

    def clean(self): #validate passwords are the same
        cleaned_data = super().clean()

        if cleaned_data.get('password') != cleaned_data.get('password2'):
            self.add_error('password2', 'The password does not match')

    def save(self):
        return User.objects.create_user( #return object of type user (create new user)
            self.cleaned_data.get('username'),
            self.cleaned_data.get('email'),
            self.cleaned_data.get('password')
        )

django_fun/categories/views.py
from django.shortcuts import render

# Create your views here.

django_fun/django_fun/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import RegisterForm
from products.models import Product

def index(request):
    products = Product.objects.all().order_by('-id')
    return render(request,'index.html', {
        'message': 'Listado de productos',
        'title': 'Productos',
        'products': products
    })

def login_view(request):
    if request.user.is_authenticated:
        return redirect('index')

    if request.method == 'POST':
        username = request.POST.get('username') #diccionario
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)
        if user:
            login(request, user) #to generate session for an user
            print('User authenticated')
            messages.success(request, 'Welcome {}'.format(user.username))
            return redirect('index')
        else:


            messages.error(request, 'User or password not valid')
    return render(request, 'users/login.html', {

    })

def logout_view(request):
        logout(request)
        messages.success(request, 'session closed successfully')
        return redirect('login')

def register(request):
    if request.user.is_authenticated:
        return redirect('index')

    form = RegisterForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        user = form.save()
        if user:
            login(request, user)
            messages.success(request, 'User created successfully')
            return redirect('index')

    return render(request, 'users/register.html', {
        'form': form
    })

django_fun/products/views.py
from django.shortcuts import render
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Product
# Create your views here.
class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')

    def get_context_data(self, **kwargs): #contexto de la clase al template
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'
        context['products'] = context['product_list']
        print(context)
        return context

class ProductDetailView(DetailView): #id -> pk
    model = Product
    template_name = 'products/product.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        print(context)
        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def get_queryset(self):
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        #SELCT * FROM products WHERE title like %valor%
        return Product.objects.filter(filters)

    def query(self):
        return self.request.GET.get('q')

    def get_context_data(self, **kwargs): #contexto de la clase al template
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()
        return context

django_fun/products/templates/products/product.html
{% extends 'base.html' %}

{% block content %}
<div class="col-3 mt-3">
  {% if product.image %}
    <img src="{{ product.image.url }}" alt="Imagen del producto" width="200" height="200">
  {% endif %}
</div>

<div class="col mt-3">
  <div class="h1">{{ product.title }}</div>
  <div class="h5 font-weight-bold">
    Price: <span class="text-danger">${{ product.price }}</span>
  </div>
  <div class="h5 font-weight-bold">
    <p> {{ product.description }}</p>
  </div>
</div>
{% endblock %}

django_fun/products/templates/products/search.html
{% extends 'base.html' %}

{% block content %}
  <div class="col">
    {% include 'products/snippets/search.html' with query=query %}
    <hr>
    <p>Resultados para: {{ query }} ({{ count }})</p>
    {% include 'products/snippets/list.html' %}
  </div>
{% endblock %}

django_fun/products/templates/products/snippets/list.html
<div class="row">
  {% for key in product_list %}
    <div class="col-3 mt-5">
      {% include 'products/snippets/product.html' with key=key%}
    </div>
  {% endfor %}
</div>

django_fun/products/templates/products/snippets/product.html
<!-- Product --->
<div class="card h-100">

  {% if key.image %}
    <img src="{{ key.image.url }}" alt="Imagen del producto" height="250">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title"> {{ key.title }} </h5>
    <p class="card-text"> {{ key.description}} </p>
    <a href="{% url 'products:product' key.slug %}" class="btn btn-primary">Ver más</a>
  </div>
</div>

django_fun/products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
  <div class="input-group">
    <input type="text" name="q" value="{{ query }}" class="form-control" placeholder="Buscar">
    <div class="input-group-append">
      <input type="submit" name="" value="Buscar" class="btn btn-primary">
    </div>
  </div>
</form>

django_fun/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>
    {% include 'navbar.html'%}
    <div class="container">

      {% include 'messages.html'%}

      <div class="row mt-3">
        {% block content %}
        {% endblock %}
      </div>

    </div>
  </body>
  <script src="https://kit.fontawesome.com/3baaec7eed.js" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

django_fun/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="col">
  <h4 class="text-center"> {{ message }}</h4>
  {% include 'products/snippets/search.html' %}
  {% include 'products/snippets/list.html' %}
</div>
{% endblock %}

django_fun/templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {{% if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">
      <button type="button" class="close" data-dismiss='alert'>x</button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

django_fun/templates/navbar.html
{% url 'login' as login %}
{% url 'register' as register %}



<nav class="navbar navbar-expand-md bg-dark navbar-dark">
  <a href="{% url 'index' %}" class="navbar-brand">My Own Store</a>
  <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navb" class="navbar-collapse collapse hide">
    <ul class="nav navbar-nav ml-auto">

      {% if user.is_authenticated %}
        <li class="navbar-item">
          <a href="{% url 'logout' %}" class="nav-link">
            <span class="fas fa-sign-in-alt"></span>
            Logout
          </a>
        </li>

      {% else %}
        <li class="navbar-item {% if request.path == login %}active{% endif %}">
          <a href="{{ login }}" class="nav-link">
            <span class="fas fa-user"></span>
            Login
          </a>
        </li>
        <li class="navbar-item {% if request.path == register %}active{% endif %}">
          <a href="{{ register }}" class="nav-link">
            <span class="fas fa-user-plus"></span>
            Registry
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

django_fun/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

<div class="col">
  <h2>Login</h2>

  <!-- Formulario ----->
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" name="username" class="form-control">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" name="password" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
  </form>

</div>

{% endblock %}

django_fun/templates/users/register.html
{% extends 'base.html' %}

{% block content %}

<div class="col">
  <h2>Register</h2>

  <!-- Formulario ----->
  <form method="POST">
    {% csrf_token %}
    <!--
    <div class="form-group">
      {{ form.username.label_tag }}
      {{ form.username }}
    </div>
    <div class="form-group">
      {{ form.email.label_tag }}
      {{ form.email }}
    </div>
    <div class="form-group">
      {{ form.password.label_tag }}
      {{ form.password }}
    </div>
    -->

    {% for field in form %}
    <div class="form-group">
      {{ field.label_tag }}
      {{ field }}

      {% if field.errors %}
        {{ field.errors }}
      {% endif %}
    </div>
    {% endfor %}

    <button type="submit" class="btn btn-primary">Register</button>
  </form>
</div>

{% endblock %}